### ISSUE TITLE
Hide border of search bar 

### ISSUE THREAD

**Issue by dipak-kumawat** [dipak-kumawat/YouTube#3]
![image](https://github.com/user-attachments/assets/c99b2be3-68e1-4e32-a1fd-15f3ea13c5b6)

**Comment by ayushsharma08** [comment]
You mean that the border on highlight (that is black )should not be shown ?
if yes then assign it to me .

**Comment by ayushsharma08** [comment]
working on it

**Comment by dipak-kumawat** [comment]
thanks for contributing 👍
